package com.pixelpoint.mediadownloader

object DownloadServiceContract {
    const val ACTION_START = "com.pixelpoint.mediadownloader.action.START_DOWNLOAD"
    const val ACTION_CANCEL = "com.pixelpoint.mediadownloader.action.CANCEL_DOWNLOAD"
    const val ACTION_TASK_STARTED = "com.pixelpoint.mediadownloader.action.TASK_STARTED"
    const val ACTION_TASK_PROGRESS = "com.pixelpoint.mediadownloader.action.TASK_PROGRESS"
    const val ACTION_TASK_COMPLETED = "com.pixelpoint.mediadownloader.action.TASK_COMPLETED"
    const val ACTION_TASK_FAILED = "com.pixelpoint.mediadownloader.action.TASK_FAILED"
    const val ACTION_TASK_CANCELLED = "com.pixelpoint.mediadownloader.action.TASK_CANCELLED"
    const val ACTION_QUEUE_UPDATED = "com.pixelpoint.mediadownloader.action.QUEUE_UPDATED"

    const val EXTRA_TASK_ID = "task_id"
    const val EXTRA_URL = "url"
    const val EXTRA_TITLE = "title"
    const val EXTRA_FILE_PATH = "file_path"
    const val EXTRA_ENGINE_VERSION = "engine_version"
    const val EXTRA_ERROR = "error"
    const val EXTRA_STATUS = "status"
    const val EXTRA_STAGE = "stage"
    const val EXTRA_CREATED_AT = "created_at"
    const val EXTRA_PROGRESS = "progress"
    const val EXTRA_DOWNLOADED_BYTES = "downloaded_bytes"
    const val EXTRA_TOTAL_BYTES = "total_bytes"
    const val EXTRA_SPEED_BYTES_PER_SECOND = "speed_bytes_per_second"
    const val EXTRA_MESSAGE = "message"
    const val EXTRA_QUEUE = "queue"
    const val EXTRA_FORMAT_SELECTOR = "format_selector"
    const val EXTRA_FORMAT_LABEL = "format_label"
    const val EXTRA_THUMBNAIL_URL = "thumbnail_url"
    const val EXTRA_REQUIRES_MEDIA_MERGE = "requires_media_merge"
    const val EXTRA_EXPORTED_PATH = "exported_path"
    const val EXTRA_EXPORTED_URI = "exported_uri"
}
